### ISSUE TITLE
Recordings showing wrong camera

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-dashboardv2#363] opened 2019-12-10 14:50 UTC
![image](https://user-images.githubusercontent.com/13561999/70539905-3b0efa80-1b5c-11ea-9e82-2fa80db247e5.png)

I don't really know how to replicate it but it happens when you switch between cameras.

**Comment by affan00** [comment] 2019-12-16 09:59
I've tested it many times with many cameras but not able to reproduce it, So I am closing this issue, Will keep an issue on this thing.

**Closed by affan00** 2019-12-16 09:59 UTC
