### ISSUE TITLE
There should be no white space at the bottom of the recording page.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboardv2#184] opened 2019-11-01 05:05 UTC
we can increase the image size more and shrink the width of the calendar to fit. It would be better if we can achieve this using default styling (classes).

**Comment by marcoherbst** [comment] 2019-11-14 09:34
Duplicate of this:
https://github.com/evercam/evercam-dashboardv2/issues/191

**Closed** 2019-11-18 16:39 UTC
