### ISSUE TITLE
Louisa's Share bug - added 4 emails and could not share.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboardv2#361] opened 2019-12-10 12:53 UTC
Emailed details to @affan00

**Comment by affan00** [comment] 2019-12-11 09:33
After making changes in the share, I and Louisa are not able to reproduce this error. Tried with multiple email addresses, share request was successful. So, I am closing this issue now.

**Closed by affan00** 2019-12-11 09:33 UTC
